# INSTALLING REQUIREMENTS

In [ ]:
!pip install pandas 
!pip install numpy 
!pip install Faker 
!pip install seaborn 
!pip install matplotlib 
!pip install scikit-learn 
!pip install kneed

In [1]:
import pandas as pd

df = pd.read_csv("clustered_dataset.csv")
df

,name,surname,gender,searching_gender,age,interests,latitude,longitude,acting,advertising,...,web design,weightlifting,windsurfing,wine tasting,woodworking,wrestling,writing,yachting,yoga,Cluster #
0,Beth,Shaw,F,M,23,"Roller hockey, Movies, Gaming, Paragliding, Or...",42.4355,-83.4890,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,142
1,Tammy,Gray,N,F,35,"Gardening, Web design, Mathematics, Gaming",39.5204,-81.0684,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72
2,Casey,Taylor,M,M,31,"Table tennis, Judo, Food criticism, Stand-up c...",48.0572,-117.7466,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10
3,Carrie,Black,F,M,38,"Fishing, Pinball, Rock Climbing, Bar tending, ...",27.7037,-97.5718,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100
4,Stephanie,Martinez,F,F,28,"Art history, Gymnastics, Rappelling, Advertisi...",38.4810,-100.4663,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Eric,Hudson,M,N,37,"Art, Food styling, Soccer, Billiards",35.5857,-95.0901,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7
4996,Kathleen,Thompson,F,N,31,"Woodworking, Card games, Marketing, Bouldering...",46.7968,-122.8680,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,42
4997,Christina,Johnson,F,N,19,"Jogging, Baking, Puzzle solving",43.3082,-110.7443,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45
4998,Anthony,Roberson,M,B,33,"Knitting, Muay Thai, Bouldering",40.9222,-72.3533,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,53
4999,Amy,Walker,F,F,21,"Escape rooms, Marketing, Fitness, Board games",40.3495,-76.1391,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42